apiVersion: v1
kind: ReplicationController
metadata:
  name: replication-pod
  labels:
    env: prod
spec:
  replicas: 3
  selector:
    app: tomcatrc
  template: 
   metadata:
     name: tomcatrc
     labels:
       app: tomcatrc
   spec:
     containers:
       - name: tomcat-prod-cont
         image: lerndevops/tomcat:8.5.47

